import Head from "next/head";
import Object3D from "./components/Sections/Objekt3D";
import Navigation from "./components/Main/Navigation";
import Intro from "./components/Main/Intro";
import Footer from "./components/Main/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Portfolio - Metoděj Janota</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navigation />
        <Object3D />
        <Intro />
        <Footer />
      </main>
    </>
  );
}
